import localFont from "next/font/local";
import "./globals.css";

export const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const robotoMedium = localFont({
  src: "./fonts/Roboto/Roboto-Medium.ttf",
  variable: "--font-roboto-medium",
  weight: "100 400 900",
});

export const metadata = {
  title: "Pataki landing pages",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoMedium.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
